# Generated by Django 3.1.7 on 2021-03-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('Product_Price', models.CharField(max_length=10)),
                ('Product_image', models.ImageField(upload_to='')),
                ('Product_create', models.DateTimeField(auto_now_add=True)),
                ('Product_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesession_app.producttype')),
            ],
        ),
    ]
