# Generated by Django 3.1.7 on 2021-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesession_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(default=1, upload_to='Product_Photo'),
            preserve_default=False,
        ),
    ]
